GET http://localhost:3000/user/

POST http://localhost:3000/user/
Content-Type: application/json
{
   
  "secteur": "Jeunesse",
  "auteur": "Cohen, Jacqueline",
  "nbre_d_exemplaires": 5,
  "support": "Bande dessinée",
  "annee": "2021"
}

